# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: toni rib
email: tonimarierib@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts from the mind of Toni, served up hot for your reading pleasure.
baseurl: "/personal-blog" # the subpath of your site, e.g. /blog
url: "http://tonirib.github.io" # the base hostname & protocol for your site
twitter_username: tonimarierib
github_username:  tonirib

# Build settings
markdown: redcarpet
extensions: [fenced_code_blocks]
